[package]
name = "stripe_discord"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.198"
serde_derive = "1.0.198"
serde_json = "1.0.116"
serde_yaml = "0.9.34"
